apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
  annotations:
    # This gets passed down to the individual pods
    sidecar.istio.io/inject: "false"
spec:
  inputs:
    params:
    - description: docker target arg
      name: docker_target
      type: string
    - description: image target name
      name: image_name
      type: string
    - description: The build context used by Kaniko
      name: path_to_context
      type: string
    - description: The path to the dockerfile to build
      name: path_to_docker_file
      type: string
    - description: pod container image
      name: container_image
      type: string
    - description: Where the components manifest dir is
      name: path_to_manifests_dir
      type: string  
    resources:
    - name: kubeflow
      type: git
    - name: manifests
      type: git
  outputs:
    resources:
    - name: $(image_name)
      type: image
  steps:
  - name: build-push
    image: gcr.io/kaniko-project/executor:v0.11.0
    command:
    - /kaniko/executor
    - --dockerfile=/workspace/$(inputs.resources.kubeflow.name)/$(inputs.params.path_to_docker_file)
    - --target=$(inputs.params.docker_target)
    - --destination=$(outputs.resources.$(inputs.params.image_name).url)
    - --context=/workspace/$(inputs.resources.kubeflow.name)/$(inputs.params.path_to_context)
    - --digest-file=/workspace/$(inputs.params.image_name)-digest      
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/user-gcp-sa.json 
    volumeMounts:
    - mountPath: /secret
      name: gcp-credentials
  - name: update-manifests
    workingDir: /workspace/$(inputs.resources.manifests.name)/$(inputs.params.path_to_manifests_dir)
    image: $(inputs.params.container_image)
    command:
    - /workspace/$(inputs.resources.kubeflow.name)/py/kubeflow/kubeflow/ci/rebuild-manifests.sh
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/gcp-credentials/user-gcp-sa.json
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-token
          key: github_token
    envFrom:
    - configMapRef:
        name: ci-pipeline-run-parameters
    volumeMounts:
    - mountPath: /secret
      name: gcp-credentials
  volumes:
  - name: gcp-credentials
    secret:
      secretName: user-gcp-sa
  - name: github-token
    secret:
      secretName: github-token