apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-conformance
  namespace: kf-conformance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib-conformance
  template:
    metadata:
      labels:
        app: katib-conformance
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: kf-conformance
      containers:
      - name: katib-container
        image: kubeflowkatib/katib-conformance:v1beta1-195ce77
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
          requests:
            memory: "64Mi"
            cpu: "0.5"
