name: CentralDashboard-angular Frontend Tests
on:
  pull_request:
    paths:
      - components/centraldashboard-angular/frontend/**

jobs:
  frontend-format-lint-check:
    name: Check code format and lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Check frontend code formatting
        run: |
          cd components/centraldashboard-angular/frontend/
          npm i
          npm run format:check

      - name: Check frontend code linting
        run: |
          cd components/centraldashboard-angular/frontend
          npm i
          npm run lint-check

  run-frontend-unittests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run unit tests
        run: |
          cd components/centraldashboard-angular/frontend/
          npm i
          npm run test:prod
