name: Build & Apply CentralDashboard manifests in KinD
on:
  pull_request:
    paths:
      - components/centraldashboard/manifests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/centraldashboard/manifests
        kubectl create ns kubeflow
        kustomize build overlays/kserve | kubectl apply -f -
