name: Build & Publish CentralDashboard Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run CentralDashboard build
      run: |
        cd components/centraldashboard
        export IMG=docker.io/kubeflownotebookswg/centraldashboard
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f Dockerfile .

    - name: Run CentralDashboard push
      if: github.event_name == 'push'
      run: |
        cd components/centraldashboard
        export IMG=docker.io/kubeflownotebookswg/centraldashboard
        export TAG=$(git describe --tags --always);
        docker push ${IMG}:${TAG}
