name: Build & Publish CentralDashboard Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/centraldashboard/**

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/centraldashboard

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run CentralDashboard build
      run: |
        cd components/centraldashboard
        make docker-build

    - name: Run CentralDashboard push
      run: |
        cd components/centraldashboard
        make docker-push
