name: Frontend Lint
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/common/frontend/**
      - components/crud-web-apps/jupyter/frontend/**
      - components/crud-web-apps/tensorboards/frontend/**
      - components/crud-web-apps/volumes/frontend/**

jobs:
  lint-common-code:
    name: Common code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Lint common
      run: |
        cd components/crud-web-apps/common/frontend/kubeflow-common-lib
        npm i
        npm run lint-check

  lint-jwa-code:
    name: Jupyter web app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Lint jupyter web app
      run: |
        cd components/crud-web-apps/jupyter/frontend
        npm i
        npm run lint-check

  lint-twa-code:
    name: TensorBoards web app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Lint tensorboards
      run: |
        cd components/crud-web-apps/tensorboards/frontend
        npm i
        npm run lint-check

  lint-vwa-code:
    name: Volumes web app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Lint Volumes web app
      run: |
        cd components/crud-web-apps/volumes/frontend
        npm i
        npm run lint-check
