name: Build & Publish RStudio Tidyverse Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/rstudio-tidyverse/**
      - components/example-notebook-servers/rstudio/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  TAG: $(git describe --tags --always --dirty)
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build -C rstudio-tidyverse
    
    - name: Push Notebook Server images
      run: |
        docker tag rstudio-tidyverse:${{env.TAG}} ${{env.REGISTRY}}/rstudio-tidyverse:${{env.TAG}}
        docker push ${{env.REGISTRY}}/rstudio-tidyverse:${{env.TAG}}

    - name: Push Notebook Server images on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        docker tag rstudio-tidyverse:${{env.TAG}} ${{env.REGISTRY}}/rstudio-tidyverse:${VERSION_TAG}
        docker push ${{env.REGISTRY}}/rstudio-tidyverse:${VERSION_TAG}
      env:
        VERSION_TAG: $(cat releasing/version/VERSION)
