name: Build & Publish Jupyter SciPy Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-scipy/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-scipy/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        make docker-build -C jupyter-scipy TAG=${TAG}
    
    - name: Push Notebook Server images via their Makefile
      if: github.event_name == 'push'
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        REGISTRY ?= kubeflownotebookswg
        docker tag jupyter-scipy:${TAG} ${REGISTRY}/jupyter-scipy:${TAG}
        docker push ${REGISTRY}/jupyter-scipy:${TAG}
