name: Build & Publish Jupyter TensorFlow Full Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-tensorflow-full/**
      - components/example-notebook-servers/jupyter-tensorflow/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**

env:
  TAG: $(git describe --tags --always --dirty)
  DOCKER_USER: kubeflownotebookswg
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        make docker-build-cpu -C jupyter-tensorflow-full
        make docker-build-cuda -C jupyter-tensorflow-full
    
    - name: Push Notebook Server images
      run: |
        docker tag jupyter-tensorflow-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-full:${{env.TAG}}
        docker push ${{env.REGISTRY}}/jupyter-tensorflow-full:${{env.TAG}}
        docker tag jupyter-tensorflow-cuda-full:${{env.TAG}} ${{env.REGISTRY}}/jupyter-tensorflow-cuda-full:${{env.TAG}}
        docker push ${{env.REGISTRY}}/jupyter-tensorflow-cuda-full:${{env.TAG}}
