name: Build & Publish PodDefaults Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run PodDefaults build
      run: |
        cd components/admission-webhook
        export IMG=docker.io/kubeflownotebookswg/poddefaults-webhook
        make docker-build

    - name: Run PodDefaults push
      if: github.event_name == 'push'
      run: |
        cd components/admission-webhook
        export IMG=docker.io/kubeflownotebookswg/poddefaults-webhook
        make docker-push
