name: Build & Apply PodDefaults manifests in KinD
on:
  pull_request:
    paths:
      - components/admission-webhook/manifests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Install cert-manager
      run: |
        echo "Installing cert-manager ..."
        CERT_MANAGER_VERSION="v1.5.0"
        kubectl create namespace cert-manager
        sleep 2
        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/${CERT_MANAGER_VERSION}/cert-manager.yaml

        echo "Waiting for cert-manager to be ready ..."
        kubectl wait --for=condition=ready pod -l 'app in (cert-manager,webhook)' --timeout=180s -n cert-manager

    - name: Build & Apply manifests
      run: |
        cd components/admission-webhook/manifests
        kubectl create ns kubeflow
        kustomize build overlays/cert-manager | kubectl apply -f -
