name: Build & Publish PodDefaults Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/poddefaults-webhook
  ARCH: linux/ppc64le,linux/amd64

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-arch docker image
        run: |
          cd components/admission-webhook
          make docker-build-multi-arch

      - name: Build  and push multi-arch docker image
        if: github.event_name == 'push'
        run: |
          cd components/admission-webhook
          make docker-build-push-multi-arch
