name: Build & Publish VWA Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run VWA build
      run: |
        cd components/volumes-web-app
        export IMG=docker.io/kubeflownotebookswg/volumes-web-app
        make docker-build

    - name: Run VWA push
      if: github.event_name == 'push'
      run: |
        cd components/volumes-web-app
        export IMG=docker.io/kubeflownotebookswg/volumes-web-app
        make docker-push
